/**
 * @fileoverview The mappings for the translations service.
 * NOTE: DO NOT EDIT THIS FILE, IT IS AUTOMATICALLY GENERATED.
 * This file is generated by the `./generators/import-translations.js` file,
 * and the translations come from the `./app/common/translations.csv` file.
 */
module.exports = %s;
